

ESTADO_OPTIONS(
  ( BCN, "Baja California Norte"),
  ( BCS, "Baja California Sur"),
  ( CAMP, "Campeche"),
  ( CHI,"Chiapas"),
  ( CHIH,"Chihuahua"),
  ( COA,"Coahuila"),
  ( COL,"Colima"),
  ( DF,"Distrito Federal"),
  ( DUR,"Durango"),
  ( EM,"Estado de Mexico"),
  ( GTO,"Guanajuato"),
  ( GRO,"Guerrero"),
  ( HDO,"Hidalgo"),
  ( JCO,"Jalisco"),
  ( MCH,"Michoacan"),
  ( MRO,"Morelos"),
  ( NRT,"Nayarit"),
  ( NLN,"Nuevo Leon"),
  ( OXC,"Oaxaca"),
  ( PUE,"Puebla"),
  ( QRT,"Queretaro"),
  ( QTR,"Quintana Roo"),
  ( SNL,"San Luis Potosi"),
  ( SIN,"Sinaloa"),
  ( SNR,"Sonora"),
  ( TBC,"Tabasco"),
  ( TMP,"Tamaulipas"),
  ( TXL,"Tlaxcala"),
  ( VER,"Veracruz"),
  ( YCT,"Yucatan"),
  ( ZAC,"Zacatecas"),
  )  
  